theme: jekyll-theme-minimal
title: Carlos's Website
description: I will publish all my school Web Exercises here. Keep an eye on my website to see the best assignment results you have ever seen ;) At least i hope so...
